version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libhdf5-dev
    - libopenblas-openmp-dev
    - liblapacke-dev

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
