[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja", "tomli"]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "python/kedm/_version.py"
tag_prefix = "v"
