name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux-cuda:
    strategy:
      matrix:
        cxx: [clang++, g++]
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.1-devel
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y clang cmake git libhdf5-dev
      env:
        DEBIAN_FRONTEND: noninteractive
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build and install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.3.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=$(readlink -f ../bin/nvcc_wrapper) \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DBUILD_SHARED_LIBS=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON \
          -DKokkos_ENABLE_CUDA=ON \
          -DKokkos_ENABLE_CUDA_LAMBDA=ON \
          -DKokkos_ARCH_VOLTA70=ON ..
        make -j $(nproc)
        make install
      env:
        NVCC_WRAPPER_DEFAULT_COMPILER: ${{ matrix.cxx }}
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=/opt/kokkos/bin/nvcc_wrapper \
          -DCMAKE_BUILD_TYPE=Debug \
          -DREGISTER_TESTS=OFF \
          -DHIGHFIVE_USE_BOOST=OFF \
          -DHIGHFIVE_UNIT_TESTS=OFF \
          -DHIGHFIVE_EXAMPLES=OFF \
          -DCXXOPTS_BUILD_TESTS=OFF \
          -DCXXOPTS_BUILD_EXAMPLES=OFF \
          -DCXXOPTS_ENABLE_INSTALL=OFF ..
        make -j $(nproc)
      env:
        NVCC_WRAPPER_DEFAULT_COMPILER: clang++

  build-linux:
    strategy:
      matrix:
        cxx: [clang++-11, g++-10]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev libopenblas-dev liblapacke-dev
    - name: Build and install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.3.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DBUILD_SHARED_LIBS=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON ..
        make -j $(nproc)
        make install
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -DCMAKE_BUILD_TYPE=Debug \
          ..
        make -j $(nproc)
    - name: Run kEDM unit tests
      run: ctest
      env:
        OMP_PROC_BIND: false
      working-directory: build

  build-macos:
    strategy:
      matrix:
        cxx: [clang++, g++-10]
      fail-fast: false
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install libomp
      if: matrix.cxx == 'clang++'
      run: |
        brew install libomp
    - name: Install LAPACK
      run: |
        brew install lapack
    - name: Build and install Kokkos
      if: matrix.cxx == 'clang++'
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.3.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -DCMAKE_CXX_FLAGS="-I/usr/local/include" \
          -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib" \
          -DCMAKE_SHARED_LINKER_FLAGS="-L/usr/local/lib" \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DBUILD_SHARED_LIBS=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON ..
        make -j $(sysctl -n hw.physicalcpu_max)
        sudo make install
    - name: Build and install Kokkos
      if: matrix.cxx == 'g++-10'
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.3.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DBUILD_SHARED_LIBS=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON ..
        make -j $(sysctl -n hw.physicalcpu_max)
        sudo make install
    - name: Install HDF5
      run: brew install hdf5
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -DCMAKE_CXX_FLAGS="-I/usr/local/include" \
          -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib" \
          -DCMAKE_SHARED_LINKER_FLAGS="-L/usr/local/lib" \
          -DCMAKE_BUILD_TYPE=Debug \
          ..
        make -j $(sysctl -n hw.physicalcpu_max)
    - name: Run kEDM unit tests
      run: ctest
      env:
        OMP_PROC_BIND: false
      working-directory: build

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run clang-format
      run: |
        git ls-files '*.hpp' '*.cpp' | xargs clang-format -i
        git diff --exit-code
