name: build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

env:
  OMP_PROC_BIND: false

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run clang-format
      run: |
        git ls-files '*.hpp' '*.cpp' | xargs clang-format -i
        git diff --exit-code

  build-linux-gpu:
    strategy:
      matrix:
        cxx: [clang++, g++]
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.3.0-devel
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y clang cmake git libhdf5-dev
      env:
        DEBIAN_FRONTEND: noninteractive
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=$(pwd)/../src/thirdparty/kokkos/bin/nvcc_wrapper \
          -DCMAKE_BUILD_TYPE=Debug \
          -DKokkos_ENABLE_CUDA=ON \
          -DKokkos_ENABLE_CUDA_LAMBDA=ON \
          -DKokkos_ARCH_VOLTA70=ON \
          -DKEDM_BUILD_TESTS=OFF ..
        make -j $(nproc)
      env:
        NVCC_WRAPPER_DEFAULT_COMPILER: ${{ matrix.cxx }}

  build-linux-cpu:
    strategy:
      matrix:
        cxx: [clang++-11, g++-10]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev libopenblas-dev liblapacke-dev
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -DKokkos_ENABLE_OPENMP=ON \
          -DCMAKE_BUILD_TYPE=Debug \
          ..
        make -j $(nproc)
    - name: Run kEDM unit tests
      run: ctest
      working-directory: build

  build-macos-cpu:
    strategy:
      matrix:
        cxx: [clang++, g++-10]
      fail-fast: false
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install libomp
      if: matrix.cxx == 'clang++'
      run: |
        brew install libomp
    - name: Install HDF5
      run: brew install hdf5
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -DCMAKE_CXX_FLAGS="-I/usr/local/include" \
          -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib" \
          -DCMAKE_SHARED_LINKER_FLAGS="-L/usr/local/lib" \
          -DKokkos_ENABLE_OPENMP=ON \
          -DCMAKE_BUILD_TYPE=Debug \
          ..
        make -j $(sysctl -n hw.physicalcpu_max)
    - name: Run kEDM unit tests
      run: ctest
      working-directory: build

  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_BUILD: cp3*
          CIBW_SKIP: cp35-*
          CIBW_ARCHS: auto64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL_LINUX: scripts/prepare_wheel_build_linux.sh
          CIBW_BEFORE_ALL_MACOS: scripts/prepare_wheel_build_macos.sh
          CIBW_BEFORE_BUILD_MACOS: pip install --force-reinstall git+https://github.com/matthew-brett/delocate.git@52b9185ff6ebb643392286242ea06417143dadb7
          CIBW_ENVIRONMENT_MACOS: "CXX=g++-10"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/python
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build-wheels-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        env:
          CIBW_BUILD: cp3*
          CIBW_SKIP: cp35-*
          CIBW_ARCHS: auto64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL_LINUX: scripts/prepare_wheel_build_linux_gpu.sh
          CIBW_ENVIRONMENT_LINUX: "PATH=$PATH:/usr/local/cuda/bin"

  publish-wheels:
    needs: [build-wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
