name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build and install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.1.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON ..
        make -j $(nproc)
        make install
    - name: Install HDF5
      run: sudo apt-get install -y libhdf5-dev
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make -j $(nproc)
    - name: Run kEDM unit tests
      run: ctest
      env:
        OMP_PROC_BIND: false
      working-directory: build

  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build and install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.1.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=$(which g++-9) \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON ..
        make -j $(nproc)
        sudo make install
    - name: Install HDF5
      run: brew install hdf5
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=$(which g++-9) \
          -DCMAKE_BUILD_TYPE=Debug \
          ..
        make -j $(sysctl -n hw.physicalcpu_max)
    - name: Run kEDM unit tests
      run: ctest
      env:
        OMP_PROC_BIND: false
      working-directory: build

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run clang-format
      run: |
        git ls-files '*.hpp' '*.cpp' | xargs clang-format -i
        git diff --exit-code
