name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-cuda:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:10.2-devel
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y software-properties-common wget
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor > /etc/apt/trusted.gpg.d/kitware.gpg
        add-apt-repository -y ppa:git-core/ppa
        apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ bionic main'
        apt-get install -y clang cmake git libhdf5-dev
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build and install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.1.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=$(readlink -f ../bin/nvcc_wrapper) \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DBUILD_SHARED_LIBS=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON \
          -DKokkos_ENABLE_CUDA=ON \
          -DKokkos_ENABLE_CUDA_LAMBDA=ON \
          -DKokkos_ARCH_PASCAL61=ON ..
        make -j $(nproc)
        make install
      env:
        NVCC_WRAPPER_DEFAULT_COMPILER: clang++
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=/opt/kokkos/bin/nvcc_wrapper \
          -DCMAKE_BUILD_TYPE=Debug \
          -DREGISTER_TESTS=OFF \
          -DHIGHFIVE_USE_BOOST=OFF \
          -DHIGHFIVE_UNIT_TESTS=OFF \
          -DHIGHFIVE_EXAMPLES=OFF \
          -DCXXOPTS_BUILD_TESTS=OFF \
          -DCXXOPTS_BUILD_EXAMPLES=OFF \
          -DCXXOPTS_ENABLE_INSTALL=OFF ..
        make -j $(nproc)
      env:
        NVCC_WRAPPER_DEFAULT_COMPILER: clang++

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build and install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.1.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DBUILD_SHARED_LIBS=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON ..
        make -j $(nproc)
        make install
    - name: Install HDF5
      run: sudo apt-get install -y libhdf5-dev
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make -j $(nproc)
    - name: Run kEDM unit tests
      run: ctest
      env:
        OMP_PROC_BIND: false
      working-directory: build

  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build and install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos.git
        cd kokkos
        git checkout 3.1.00
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=$(which g++-9) \
          -DCMAKE_INSTALL_PREFIX=/opt/kokkos \
          -DBUILD_SHARED_LIBS=ON \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON ..
        make -j $(nproc)
        sudo make install
    - name: Install HDF5
      run: brew install hdf5
    - name: Build kEDM
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_CXX_COMPILER=$(which g++-9) \
          -DCMAKE_BUILD_TYPE=Debug \
          ..
        make -j $(sysctl -n hw.physicalcpu_max)
    - name: Run kEDM unit tests
      run: ctest
      env:
        OMP_PROC_BIND: false
      working-directory: build

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run clang-format
      run: |
        git ls-files '*.hpp' '*.cpp' | xargs clang-format -i
        git diff --exit-code
